trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    echo "Step 1: Updating package lists..."
    sudo apt-get update

    echo "Step 2: Installing necessary packages..."
    sudo apt-get install -y curl git

    echo "Step 3: Installing Terraform..."
    curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg
    echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
    sudo apt-get update && sudo apt-get install terraform

    echo "Step 4: Verifying Terraform installation..."
    terraform --version

    echo "Step 5: Initializing Terraform..."
    terraform init -backend-config="path/to/backend/config"

    echo "Step 6: Planning Terraform deployment..."
    terraform plan -out=terraform.tfplan

    echo "Step 7: Applying Terraform configuration..."
    terraform apply -auto-approve terraform.tfplan
  displayName: 'Run Terraform Steps'
